//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Chem4Word.Searcher.ChEBIPlugin.ChEBI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChebiWebServiceBinding", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class ChebiWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getLiteEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCompleteEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCompleteEntityByListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOntologyParentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOntologyChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllOntologyChildrenInPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStructureSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUpdatedPolymerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChebiWebServiceService() {
            this.Url = global::Chem4Word.Searcher.ChEBIPlugin.Properties.Settings.Default.Chem4Word_Searcher_ChEBIPlugin_uk_ac_ebi_www_ChebiWebServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getLiteEntityCompletedEventHandler getLiteEntityCompleted;
        
        /// <remarks/>
        public event getCompleteEntityCompletedEventHandler getCompleteEntityCompleted;
        
        /// <remarks/>
        public event getCompleteEntityByListCompletedEventHandler getCompleteEntityByListCompleted;
        
        /// <remarks/>
        public event getOntologyParentsCompletedEventHandler getOntologyParentsCompleted;
        
        /// <remarks/>
        public event getOntologyChildrenCompletedEventHandler getOntologyChildrenCompleted;
        
        /// <remarks/>
        public event getAllOntologyChildrenInPathCompletedEventHandler getAllOntologyChildrenInPathCompleted;
        
        /// <remarks/>
        public event getStructureSearchCompletedEventHandler getStructureSearchCompleted;
        
        /// <remarks/>
        public event getUpdatedPolymerCompletedEventHandler getUpdatedPolymerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getLiteEntityResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getLiteEntityResponse getLiteEntity([System.Xml.Serialization.XmlElementAttribute("getLiteEntity", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getLiteEntity getLiteEntity1) {
            object[] results = this.Invoke("getLiteEntity", new object[] {
                        getLiteEntity1});
            return ((getLiteEntityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getLiteEntityAsync(getLiteEntity getLiteEntity1) {
            this.getLiteEntityAsync(getLiteEntity1, null);
        }
        
        /// <remarks/>
        public void getLiteEntityAsync(getLiteEntity getLiteEntity1, object userState) {
            if ((this.getLiteEntityOperationCompleted == null)) {
                this.getLiteEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLiteEntityOperationCompleted);
            }
            this.InvokeAsync("getLiteEntity", new object[] {
                        getLiteEntity1}, this.getLiteEntityOperationCompleted, userState);
        }
        
        private void OngetLiteEntityOperationCompleted(object arg) {
            if ((this.getLiteEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLiteEntityCompleted(this, new getLiteEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getCompleteEntityResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getCompleteEntityResponse getCompleteEntity([System.Xml.Serialization.XmlElementAttribute("getCompleteEntity", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getCompleteEntity getCompleteEntity1) {
            object[] results = this.Invoke("getCompleteEntity", new object[] {
                        getCompleteEntity1});
            return ((getCompleteEntityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getCompleteEntityAsync(getCompleteEntity getCompleteEntity1) {
            this.getCompleteEntityAsync(getCompleteEntity1, null);
        }
        
        /// <remarks/>
        public void getCompleteEntityAsync(getCompleteEntity getCompleteEntity1, object userState) {
            if ((this.getCompleteEntityOperationCompleted == null)) {
                this.getCompleteEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCompleteEntityOperationCompleted);
            }
            this.InvokeAsync("getCompleteEntity", new object[] {
                        getCompleteEntity1}, this.getCompleteEntityOperationCompleted, userState);
        }
        
        private void OngetCompleteEntityOperationCompleted(object arg) {
            if ((this.getCompleteEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleteEntityCompleted(this, new getCompleteEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getCompleteEntityByListResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("return", IsNullable=false)]
        public Entity[] getCompleteEntityByList([System.Xml.Serialization.XmlArrayAttribute("getCompleteEntityByList", Namespace="https://www.ebi.ac.uk/webservices/chebi")] [System.Xml.Serialization.XmlArrayItemAttribute("ListOfChEBIIds", IsNullable=false)] string[] getCompleteEntityByList1) {
            object[] results = this.Invoke("getCompleteEntityByList", new object[] {
                        getCompleteEntityByList1});
            return ((Entity[])(results[0]));
        }
        
        /// <remarks/>
        public void getCompleteEntityByListAsync(string[] getCompleteEntityByList1) {
            this.getCompleteEntityByListAsync(getCompleteEntityByList1, null);
        }
        
        /// <remarks/>
        public void getCompleteEntityByListAsync(string[] getCompleteEntityByList1, object userState) {
            if ((this.getCompleteEntityByListOperationCompleted == null)) {
                this.getCompleteEntityByListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCompleteEntityByListOperationCompleted);
            }
            this.InvokeAsync("getCompleteEntityByList", new object[] {
                        getCompleteEntityByList1}, this.getCompleteEntityByListOperationCompleted, userState);
        }
        
        private void OngetCompleteEntityByListOperationCompleted(object arg) {
            if ((this.getCompleteEntityByListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleteEntityByListCompleted(this, new getCompleteEntityByListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getOntologyParentsResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getOntologyParentsResponse getOntologyParents([System.Xml.Serialization.XmlElementAttribute("getOntologyParents", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getOntologyParents getOntologyParents1) {
            object[] results = this.Invoke("getOntologyParents", new object[] {
                        getOntologyParents1});
            return ((getOntologyParentsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getOntologyParentsAsync(getOntologyParents getOntologyParents1) {
            this.getOntologyParentsAsync(getOntologyParents1, null);
        }
        
        /// <remarks/>
        public void getOntologyParentsAsync(getOntologyParents getOntologyParents1, object userState) {
            if ((this.getOntologyParentsOperationCompleted == null)) {
                this.getOntologyParentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOntologyParentsOperationCompleted);
            }
            this.InvokeAsync("getOntologyParents", new object[] {
                        getOntologyParents1}, this.getOntologyParentsOperationCompleted, userState);
        }
        
        private void OngetOntologyParentsOperationCompleted(object arg) {
            if ((this.getOntologyParentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOntologyParentsCompleted(this, new getOntologyParentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getOntologyChildrenResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getOntologyChildrenResponse getOntologyChildren([System.Xml.Serialization.XmlElementAttribute("getOntologyChildren", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getOntologyChildren getOntologyChildren1) {
            object[] results = this.Invoke("getOntologyChildren", new object[] {
                        getOntologyChildren1});
            return ((getOntologyChildrenResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getOntologyChildrenAsync(getOntologyChildren getOntologyChildren1) {
            this.getOntologyChildrenAsync(getOntologyChildren1, null);
        }
        
        /// <remarks/>
        public void getOntologyChildrenAsync(getOntologyChildren getOntologyChildren1, object userState) {
            if ((this.getOntologyChildrenOperationCompleted == null)) {
                this.getOntologyChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOntologyChildrenOperationCompleted);
            }
            this.InvokeAsync("getOntologyChildren", new object[] {
                        getOntologyChildren1}, this.getOntologyChildrenOperationCompleted, userState);
        }
        
        private void OngetOntologyChildrenOperationCompleted(object arg) {
            if ((this.getOntologyChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOntologyChildrenCompleted(this, new getOntologyChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getLiteEntityResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getLiteEntityResponse getAllOntologyChildrenInPath([System.Xml.Serialization.XmlElementAttribute("getAllOntologyChildrenInPath", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getAllOntologyChildrenInPath getAllOntologyChildrenInPath1) {
            object[] results = this.Invoke("getAllOntologyChildrenInPath", new object[] {
                        getAllOntologyChildrenInPath1});
            return ((getLiteEntityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllOntologyChildrenInPathAsync(getAllOntologyChildrenInPath getAllOntologyChildrenInPath1) {
            this.getAllOntologyChildrenInPathAsync(getAllOntologyChildrenInPath1, null);
        }
        
        /// <remarks/>
        public void getAllOntologyChildrenInPathAsync(getAllOntologyChildrenInPath getAllOntologyChildrenInPath1, object userState) {
            if ((this.getAllOntologyChildrenInPathOperationCompleted == null)) {
                this.getAllOntologyChildrenInPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllOntologyChildrenInPathOperationCompleted);
            }
            this.InvokeAsync("getAllOntologyChildrenInPath", new object[] {
                        getAllOntologyChildrenInPath1}, this.getAllOntologyChildrenInPathOperationCompleted, userState);
        }
        
        private void OngetAllOntologyChildrenInPathOperationCompleted(object arg) {
            if ((this.getAllOntologyChildrenInPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllOntologyChildrenInPathCompleted(this, new getAllOntologyChildrenInPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getStructureSearchResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getLiteEntityResponse getStructureSearch([System.Xml.Serialization.XmlElementAttribute("getStructureSearch", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getStructureSearch getStructureSearch1) {
            object[] results = this.Invoke("getStructureSearch", new object[] {
                        getStructureSearch1});
            return ((getLiteEntityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getStructureSearchAsync(getStructureSearch getStructureSearch1) {
            this.getStructureSearchAsync(getStructureSearch1, null);
        }
        
        /// <remarks/>
        public void getStructureSearchAsync(getStructureSearch getStructureSearch1, object userState) {
            if ((this.getStructureSearchOperationCompleted == null)) {
                this.getStructureSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStructureSearchOperationCompleted);
            }
            this.InvokeAsync("getStructureSearch", new object[] {
                        getStructureSearch1}, this.getStructureSearchOperationCompleted, userState);
        }
        
        private void OngetStructureSearchOperationCompleted(object arg) {
            if ((this.getStructureSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStructureSearchCompleted(this, new getStructureSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getUpdatedPolymerResponse", Namespace="https://www.ebi.ac.uk/webservices/chebi")]
        public getUpdatedPolymerResponse getUpdatedPolymer([System.Xml.Serialization.XmlElementAttribute("getUpdatedPolymer", Namespace="https://www.ebi.ac.uk/webservices/chebi")] getUpdatedPolymer getUpdatedPolymer1) {
            object[] results = this.Invoke("getUpdatedPolymer", new object[] {
                        getUpdatedPolymer1});
            return ((getUpdatedPolymerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getUpdatedPolymerAsync(getUpdatedPolymer getUpdatedPolymer1) {
            this.getUpdatedPolymerAsync(getUpdatedPolymer1, null);
        }
        
        /// <remarks/>
        public void getUpdatedPolymerAsync(getUpdatedPolymer getUpdatedPolymer1, object userState) {
            if ((this.getUpdatedPolymerOperationCompleted == null)) {
                this.getUpdatedPolymerOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUpdatedPolymerOperationCompleted);
            }
            this.InvokeAsync("getUpdatedPolymer", new object[] {
                        getUpdatedPolymer1}, this.getUpdatedPolymerOperationCompleted, userState);
        }
        
        private void OngetUpdatedPolymerOperationCompleted(object arg) {
            if ((this.getUpdatedPolymerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUpdatedPolymerCompleted(this, new getUpdatedPolymerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getLiteEntity {
        
        private string searchField;
        
        private SearchCategory searchCategoryField;
        
        private int maximumResultsField;
        
        private StarsCategory starsField;
        
        /// <remarks/>
        public string search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
            }
        }
        
        /// <remarks/>
        public SearchCategory searchCategory {
            get {
                return this.searchCategoryField;
            }
            set {
                this.searchCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int maximumResults {
            get {
                return this.maximumResultsField;
            }
            set {
                this.maximumResultsField = value;
            }
        }
        
        /// <remarks/>
        public StarsCategory stars {
            get {
                return this.starsField;
            }
            set {
                this.starsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum SearchCategory {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHEBI ID")]
        CHEBIID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHEBI NAME")]
        CHEBINAME,
        
        /// <remarks/>
        DEFINITION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ALL NAMES")]
        ALLNAMES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IUPAC NAME")]
        IUPACNAME,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DATABASE LINK/REGISTRY NUMBER/CITATION")]
        DATABASELINKREGISTRYNUMBERCITATION,
        
        /// <remarks/>
        FORMULA,
        
        /// <remarks/>
        MASS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MONOISOTOPIC MASS")]
        MONOISOTOPICMASS,
        
        /// <remarks/>
        CHARGE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INCHI/INCHI KEY")]
        INCHIINCHIKEY,
        
        /// <remarks/>
        SMILES,
        
        /// <remarks/>
        SPECIES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum StarsCategory {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TWO ONLY")]
        TWOONLY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("THREE ONLY")]
        THREEONLY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class UpdatedPolymer {
        
        private string updatedStructureField;
        
        private string globalFormulaField;
        
        private string globalChargeField;
        
        private string chebiIdField;
        
        /// <remarks/>
        public string updatedStructure {
            get {
                return this.updatedStructureField;
            }
            set {
                this.updatedStructureField = value;
            }
        }
        
        /// <remarks/>
        public string globalFormula {
            get {
                return this.globalFormulaField;
            }
            set {
                this.globalFormulaField = value;
            }
        }
        
        /// <remarks/>
        public string globalCharge {
            get {
                return this.globalChargeField;
            }
            set {
                this.globalChargeField = value;
            }
        }
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getUpdatedPolymerResponse {
        
        private UpdatedPolymer returnField;
        
        /// <remarks/>
        public UpdatedPolymer @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getUpdatedPolymer {
        
        private string chebiIdField;
        
        private string[] polymerisationIndexField;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("polymerisationIndex")]
        public string[] polymerisationIndex {
            get {
                return this.polymerisationIndexField;
            }
            set {
                this.polymerisationIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getStructureSearch {
        
        private string structureField;
        
        private StructureType typeField;
        
        private StructureSearchCategory structureSearchCategoryField;
        
        private int totalResultsField;
        
        private float tanimotoCutoffField;
        
        /// <remarks/>
        public string structure {
            get {
                return this.structureField;
            }
            set {
                this.structureField = value;
            }
        }
        
        /// <remarks/>
        public StructureType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public StructureSearchCategory structureSearchCategory {
            get {
                return this.structureSearchCategoryField;
            }
            set {
                this.structureSearchCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int totalResults {
            get {
                return this.totalResultsField;
            }
            set {
                this.totalResultsField = value;
            }
        }
        
        /// <remarks/>
        public float tanimotoCutoff {
            get {
                return this.tanimotoCutoffField;
            }
            set {
                this.tanimotoCutoffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum StructureType {
        
        /// <remarks/>
        MOLFILE,
        
        /// <remarks/>
        CML,
        
        /// <remarks/>
        SMILES,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum StructureSearchCategory {
        
        /// <remarks/>
        IDENTITY,
        
        /// <remarks/>
        SUBSTRUCTURE,
        
        /// <remarks/>
        SIMILARITY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getAllOntologyChildrenInPath {
        
        private string chebiIdField;
        
        private RelationshipType relationshipTypeField;
        
        private bool structureOnlyField;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        public RelationshipType relationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool structureOnly {
            get {
                return this.structureOnlyField;
            }
            set {
                this.structureOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public enum RelationshipType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is a")]
        isa,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has part")]
        haspart,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is conjugate base of")]
        isconjugatebaseof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is conjugate acid of")]
        isconjugateacidof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is tautomer of")]
        istautomerof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is enantiomer of")]
        isenantiomerof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has functional parent")]
        hasfunctionalparent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has parent hydride")]
        hasparenthydride,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("is substituent group from")]
        issubstituentgroupfrom,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("has role")]
        hasrole,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyChildrenResponse {
        
        private OntologyDataItem[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ListElement", IsNullable=false)]
        public OntologyDataItem[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class OntologyDataItem {
        
        private string chebiNameField;
        
        private string chebiIdField;
        
        private string typeField;
        
        private string statusField;
        
        private bool cyclicRelationshipField;
        
        private CommentDataItem[] commentsField;
        
        private OntologyDataItem[] ontologyElementField;
        
        /// <remarks/>
        public string chebiName {
            get {
                return this.chebiNameField;
            }
            set {
                this.chebiNameField = value;
            }
        }
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public bool cyclicRelationship {
            get {
                return this.cyclicRelationshipField;
            }
            set {
                this.cyclicRelationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public CommentDataItem[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OntologyElement")]
        public OntologyDataItem[] OntologyElement {
            get {
                return this.ontologyElementField;
            }
            set {
                this.ontologyElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class CommentDataItem {
        
        private string textField;
        
        private string dateField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyChildren {
        
        private string chebiIdField;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyParentsResponse {
        
        private OntologyDataItem[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ListElement", IsNullable=false)]
        public OntologyDataItem[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getOntologyParents {
        
        private string chebiIdField;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class CompoundOriginDataItem {
        
        private string speciesTextField;
        
        private string speciesAccessionField;
        
        private string componentTextField;
        
        private string componentAccessionField;
        
        private string strainTextField;
        
        private string strainAccessionField;
        
        private string sourceTypeField;
        
        private string sourceAccessionField;
        
        /// <remarks/>
        public string speciesText {
            get {
                return this.speciesTextField;
            }
            set {
                this.speciesTextField = value;
            }
        }
        
        /// <remarks/>
        public string speciesAccession {
            get {
                return this.speciesAccessionField;
            }
            set {
                this.speciesAccessionField = value;
            }
        }
        
        /// <remarks/>
        public string componentText {
            get {
                return this.componentTextField;
            }
            set {
                this.componentTextField = value;
            }
        }
        
        /// <remarks/>
        public string componentAccession {
            get {
                return this.componentAccessionField;
            }
            set {
                this.componentAccessionField = value;
            }
        }
        
        /// <remarks/>
        public string strainText {
            get {
                return this.strainTextField;
            }
            set {
                this.strainTextField = value;
            }
        }
        
        /// <remarks/>
        public string strainAccession {
            get {
                return this.strainAccessionField;
            }
            set {
                this.strainAccessionField = value;
            }
        }
        
        /// <remarks/>
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceAccession {
            get {
                return this.sourceAccessionField;
            }
            set {
                this.sourceAccessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class StructureDataItem {
        
        private string structureField;
        
        private string typeField;
        
        private string dimensionField;
        
        private bool defaultStructureField;
        
        private bool defaultStructureFieldSpecified;
        
        private CommentDataItem[] commentsField;
        
        /// <remarks/>
        public string structure {
            get {
                return this.structureField;
            }
            set {
                this.structureField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
            }
        }
        
        /// <remarks/>
        public bool defaultStructure {
            get {
                return this.defaultStructureField;
            }
            set {
                this.defaultStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultStructureSpecified {
            get {
                return this.defaultStructureFieldSpecified;
            }
            set {
                this.defaultStructureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public CommentDataItem[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class DataItem {
        
        private string dataField;
        
        private string typeField;
        
        private string sourceField;
        
        private CommentDataItem[] commentsField;
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public CommentDataItem[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class Entity {
        
        private string chebiIdField;
        
        private string chebiAsciiNameField;
        
        private string definitionField;
        
        private string statusField;
        
        private string smilesField;
        
        private string inchiField;
        
        private string inchiKeyField;
        
        private string chargeField;
        
        private string massField;
        
        private string monoisotopicMassField;
        
        private int entityStarField;
        
        private bool entityStarFieldSpecified;
        
        private string[] secondaryChEBIIdsField;
        
        private DataItem[] synonymsField;
        
        private DataItem[] iupacNamesField;
        
        private DataItem[] formulaeField;
        
        private DataItem[] registryNumbersField;
        
        private DataItem[] citationsField;
        
        private StructureDataItem[] chemicalStructuresField;
        
        private DataItem[] databaseLinksField;
        
        private OntologyDataItem[] ontologyParentsField;
        
        private OntologyDataItem[] ontologyChildrenField;
        
        private CommentDataItem[] generalCommentsField;
        
        private CompoundOriginDataItem[] compoundOriginsField;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        public string chebiAsciiName {
            get {
                return this.chebiAsciiNameField;
            }
            set {
                this.chebiAsciiNameField = value;
            }
        }
        
        /// <remarks/>
        public string definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string smiles {
            get {
                return this.smilesField;
            }
            set {
                this.smilesField = value;
            }
        }
        
        /// <remarks/>
        public string inchi {
            get {
                return this.inchiField;
            }
            set {
                this.inchiField = value;
            }
        }
        
        /// <remarks/>
        public string inchiKey {
            get {
                return this.inchiKeyField;
            }
            set {
                this.inchiKeyField = value;
            }
        }
        
        /// <remarks/>
        public string charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        public string mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        public string monoisotopicMass {
            get {
                return this.monoisotopicMassField;
            }
            set {
                this.monoisotopicMassField = value;
            }
        }
        
        /// <remarks/>
        public int entityStar {
            get {
                return this.entityStarField;
            }
            set {
                this.entityStarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityStarSpecified {
            get {
                return this.entityStarFieldSpecified;
            }
            set {
                this.entityStarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecondaryChEBIIds")]
        public string[] SecondaryChEBIIds {
            get {
                return this.secondaryChEBIIdsField;
            }
            set {
                this.secondaryChEBIIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Synonyms")]
        public DataItem[] Synonyms {
            get {
                return this.synonymsField;
            }
            set {
                this.synonymsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IupacNames")]
        public DataItem[] IupacNames {
            get {
                return this.iupacNamesField;
            }
            set {
                this.iupacNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Formulae")]
        public DataItem[] Formulae {
            get {
                return this.formulaeField;
            }
            set {
                this.formulaeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryNumbers")]
        public DataItem[] RegistryNumbers {
            get {
                return this.registryNumbersField;
            }
            set {
                this.registryNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Citations")]
        public DataItem[] Citations {
            get {
                return this.citationsField;
            }
            set {
                this.citationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChemicalStructures")]
        public StructureDataItem[] ChemicalStructures {
            get {
                return this.chemicalStructuresField;
            }
            set {
                this.chemicalStructuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatabaseLinks")]
        public DataItem[] DatabaseLinks {
            get {
                return this.databaseLinksField;
            }
            set {
                this.databaseLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OntologyParents")]
        public OntologyDataItem[] OntologyParents {
            get {
                return this.ontologyParentsField;
            }
            set {
                this.ontologyParentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OntologyChildren")]
        public OntologyDataItem[] OntologyChildren {
            get {
                return this.ontologyChildrenField;
            }
            set {
                this.ontologyChildrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GeneralComments")]
        public CommentDataItem[] GeneralComments {
            get {
                return this.generalCommentsField;
            }
            set {
                this.generalCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompoundOrigins")]
        public CompoundOriginDataItem[] CompoundOrigins {
            get {
                return this.compoundOriginsField;
            }
            set {
                this.compoundOriginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getCompleteEntityResponse {
        
        private Entity returnField;
        
        /// <remarks/>
        public Entity @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getCompleteEntity {
        
        private string chebiIdField;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class LiteEntity {
        
        private string chebiIdField;
        
        private string chebiAsciiNameField;
        
        private float searchScoreField;
        
        private bool searchScoreFieldSpecified;
        
        private int entityStarField;
        
        private bool entityStarFieldSpecified;
        
        /// <remarks/>
        public string chebiId {
            get {
                return this.chebiIdField;
            }
            set {
                this.chebiIdField = value;
            }
        }
        
        /// <remarks/>
        public string chebiAsciiName {
            get {
                return this.chebiAsciiNameField;
            }
            set {
                this.chebiAsciiNameField = value;
            }
        }
        
        /// <remarks/>
        public float searchScore {
            get {
                return this.searchScoreField;
            }
            set {
                this.searchScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchScoreSpecified {
            get {
                return this.searchScoreFieldSpecified;
            }
            set {
                this.searchScoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int entityStar {
            get {
                return this.entityStarField;
            }
            set {
                this.entityStarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityStarSpecified {
            get {
                return this.entityStarFieldSpecified;
            }
            set {
                this.entityStarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ebi.ac.uk/webservices/chebi")]
    public partial class getLiteEntityResponse {
        
        private LiteEntity[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ListElement", IsNullable=false)]
        public LiteEntity[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getLiteEntityCompletedEventHandler(object sender, getLiteEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLiteEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLiteEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getLiteEntityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getLiteEntityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCompleteEntityCompletedEventHandler(object sender, getCompleteEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompleteEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompleteEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getCompleteEntityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getCompleteEntityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCompleteEntityByListCompletedEventHandler(object sender, getCompleteEntityByListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompleteEntityByListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompleteEntityByListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Entity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Entity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getOntologyParentsCompletedEventHandler(object sender, getOntologyParentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOntologyParentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOntologyParentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getOntologyParentsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getOntologyParentsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getOntologyChildrenCompletedEventHandler(object sender, getOntologyChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOntologyChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOntologyChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getOntologyChildrenResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getOntologyChildrenResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getAllOntologyChildrenInPathCompletedEventHandler(object sender, getAllOntologyChildrenInPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllOntologyChildrenInPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllOntologyChildrenInPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getLiteEntityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getLiteEntityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getStructureSearchCompletedEventHandler(object sender, getStructureSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStructureSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStructureSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getLiteEntityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getLiteEntityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getUpdatedPolymerCompletedEventHandler(object sender, getUpdatedPolymerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUpdatedPolymerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUpdatedPolymerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getUpdatedPolymerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getUpdatedPolymerResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591